### ISSUE TITLE
Feature request: Support non low-latency streams

### ISSUE THREAD

**Issue by salevdns** [2bc4/twitch-hls-client#13]
First off, thanks for this great tool!

Some streams do not have low-latency-mode available, and therefore their m3u8 files lack the `#EXT-X-TWITCH-PREFETCH` entries.
Currently, such streams fail with: `Invalid or missing prefetch URLs`.

**Comment by 2bc4** [comment]
I think supporting this directly is currently out of scope because a non low latency stream is just a normal HLS stream, and most players already support that. 

As a workaround this will now open the player with the playlist URL if the stream is not a low latency stream. Please reopen if you encounter any issues with it.

**Comment by salevdns** [comment]
The workaround works fine, thanks.
